# -*- coding: utf-8 -*-
"""inst_760_project_2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v3mpMC1EBEhDoTv9Yy3FMTKRLJ9NQvXZ
"""

#Import packages
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#Read csv file
df=pd.read_csv('Netflix.csv')

#First 5 rows
df.head()

# Set Whitegrid
sns.set_style(style="whitegrid")

# Define rating groups function
def netflix_rating_groups(r):
    if r in ['G', 'TV-G', 'TV-Y']:
        return 'General'
    elif r in ['PG', 'PG-13', 'TV-PG', 'TV-Y7']:
        return 'Teen'
    elif r in ['R', 'TV-MA', 'NC-17']:
        return 'Mature'
    else:
        return 'Other'

# Apply rating groups
df['group_rating'] = df['rating'].apply(netflix_rating_groups)

# Extract duration as float as some durations are not numerical
df['duration_mins'] = df['duration'].str.extract(r'(\d+)').astype(float)

#Scatterplor
sns.scatterplot(
    data=df,
    x='release_year',
    y='duration_mins',
    hue='group_rating',
    style='type',
    palette='colorblind',
    alpha=0.8,
    edgecolor='black',
    s=70
)

# Labeling the plot
plt.title("Netflix Media: Duration vs. Release Year", fontsize=18, weight='bold')
plt.xlabel("Release Year")
plt.ylabel("Duration (in minutes)")
plt.xticks(rotation=45)
plt.legend(title="Rating Group and Type of Media", loc='upper left', bbox_to_anchor=(1, 1))
plt.show()
plt.savefig("Netflix Scatterplot.png")