# -*- coding: utf-8 -*-
"""project_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FA-Ijt2oOm3sqJXZMVy7_iP8sqHUmf8w
"""

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# read csv file
df = pd.read_csv("ev_specs.csv")

# display first five rows
df.head()

# create scatterplot
g = sns.relplot(x = "battery_capacity_kWh",
            y = "top_speed_kmh",
            data = df,
            kind = "scatter",
            style = "car_body_type",
            hue = "drivetrain",
            size = "range_km")

# adding title and cleaning up labels
g.fig.suptitle("Relationship Between Battery Capacity and Top Speed of EVs",
               y = 1.04)
g.set(xlabel = "Battery Capacity (kWh)",
      ylabel = "Top Speed (kmh)")

# customize the legend
legend = g._legend
for text in legend.get_texts():
    txt = text.get_text()
    if txt == "drivetrain":
        text.set_text("Drivetrain") # rename subheading
        text.set_fontweight("bold") # make subheading bold
    elif txt == "car_body_type":
        text.set_text("Car Body Type") # rename subheading
        text.set_fontweight("bold") # make subheading bold
    elif txt == "range_km":
        text.set_text("Range (km)") # rename subheading
        text.set_fontweight("bold") # make subheading bold

# add annotation
ax = g.ax  # get the main axes object
ax.annotate(
    "Maserati GranTurismo Folgore;\nTop Overall Performer",
    xy=(83, 325),                # location of top outlier point
    xytext=(35, 1),             # offset the text position
    textcoords='offset points',
    arrowprops=dict(arrowstyle="->"),
    fontsize=8,
    color="darkred"
)

# save plot as image
plt.savefig("plot2.png", dpi=300, bbox_inches='tight')
