# -*- coding: utf-8 -*-
"""Project 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/avkash10/project-2.bbb64a17-446d-4fcb-ab29-5addb62aab55.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20250803/auto/storage/goog4_request%26X-Goog-Date%3D20250803T223141Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D364c46426014c097d2ca99051a13213385059d1cbd023e6cc9600ff225507826bb817a035ee471b30fd5a34c0ceed12953b4d5b157b40d7ee95692b44eec8ed34438a59df7761b3f3d2303dfcdfd193d08896cfb97b346fc2056d9936953ab2bbeb1a798b7d0eca525ba8c50acbd1d519236c7cae5f4b03641c6bd92004bbe6f76a7ebac8ea4f5d6c4dabb75baba501c8c004385572dca56e9d93479d25e1cc7fd774e68e987df0405d3498d4057465addd1ecc9662abcb814c0074b3d3b6c5e8e93f1d960db50f926795a6ed53f49d099d496d76c85f3a4b95af514077c911cbdb34e5983f6dda726b506296cb42709de3979c1893d418b38a30eacbbd37e8c
"""

# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.
import kagglehub
unsdsn_world_happiness_path = kagglehub.dataset_download('unsdsn/world-happiness')

print('Data source import complete.')

# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All"
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load the 2019 World Happiness data
df = pd.read_csv('/kaggle/input/world-happiness/2019.csv')

df.columns

plt.rcParams.update({'font.family': 'DejaVu Sans', 'axes.titlesize': 18, 'axes.labelsize': 14})
# Set up the figure size and style for the plot
plt.figure(figsize=(12, 8))
sns.set_style("whitegrid")

# Make the scatter plot
# Bubble size shows happiness score, color shows freedom to make life choices
plot = sns.scatterplot(
    x=df['GDP per capita'],
    y=df['Healthy life expectancy'],
    size=df['Score'],
    hue=df['Freedom to make life choices'],
    sizes=(40, 400),
    alpha=0.6,
    edgecolor='gray',
    palette='coolwarm',
    legend='brief'
)

# Add title and axis labels
plt.title('GDP vs Life Expectancy with Happiness and Freedom Levels', fontsize=15)
plt.xlabel('GDP per Capita')
plt.ylabel('Healthy Life Expectancy')

# Fix the legend to have a clear title
handles, labels = plot.get_legend_handles_labels()
plot.legend(handles=handles, labels=labels, title='Happiness: Freedom & Score', bbox_to_anchor=(1.02, 1), loc='upper left')

# Highlight Finland with a black hollow circle around its bubble
finland = df[df['Country or region'] == 'Finland'].iloc[0]

plt.scatter(
    finland['GDP per capita'], finland['Healthy life expectancy'],
    s=600,               # larger size for emphasis
    facecolors='none',   # hollow circle
    edgecolors='black',
    linewidth=2,
    label='Finland (Highest Score)'
)

# Update legend to include Finland highlight
plt.legend(loc='upper left', bbox_to_anchor=(1.02, 1))

# Adjust layout and save plot image
plt.tight_layout()
plt.savefig('happiness_plot.png', dpi=300)
plt.show()

"""This bubble chart visualizes the relationship between GDP per capita and healthy life expectancy for countries in 2019 specifically, with bubble size representing the overall happiness score and color indicating the level of freedom to make life choices. Larger bubbles correspond to happier countries, and the color gradient from blue to red reflects lower to higher freedom levels.

To highlight the country with the highest happiness score as people may just assume highest point on graph means thats the top country, Finland's data point is emphasized with a distinct black hollow circle around its bubble, making it stand out clearly without cluttering the plot with text. The legend also states Finland as highest score.

This single plot combines multiple data dimensions such as economic, health, social freedom, and happiness—into a visualization that is understandable and effective.
"""