# -*- coding: utf-8 -*-
"""inst_760_project_3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p6Qgv4Ec0iTC2ItYw16lGPCKGIFtYTj_
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv('CarRentalData.csv')

#Histogram of Distribution of car ratings
sns.set(style='whitegrid')
plt.figure(figsize=(8,5))
sns.histplot(df['rating'], bins=20, color='blue')
plt.title('Distribution of Car Ratings')
plt.suptitle('Customers rate vehicles highly overall.', fontsize=10, y=0.95)
plt.xlabel('Rating')
plt.ylabel('Count')
plt.tight_layout()
plt.show()
plt.clf()
plt.savefig('histogramratings.png')

#Bar Chart of Number of trips by vehicle type
sns.set(style='whitegrid')
trips_by_type = df.groupby('vehicle.type')['renterTripsTaken'].sum().reset_index()
plt.figure(figsize=(8,5))
sns.barplot(data=trips_by_type, x='vehicle.type', y='renterTripsTaken', palette='muted', hue='vehicle.type')
plt.title('Total Number of Trips by Vehicle Type')
plt.suptitle('Cars are rented the most?', fontsize=10, y=0.95)
plt.xlabel('Vehicle Type')
plt.ylabel('Total Trips Taken')
plt.tight_layout()
plt.savefig('barnumberoftrips.png')
plt.show()
plt.clf()

#Bar Chart of Average daily rate by fuel type
sns.set(style='whitegrid')
plt.figure(figsize=(8,5))
sns.barplot(data=df, x='fuelType', y='rate.daily', ci=None, palette='Dark2', hue='vehicle.type')
plt.title('Average Daily Rental Rate (By Fuel Type)')
plt.suptitle('Electric and Diesel Vehicles Cost More to Rent', fontsize=10, y=0.95)
plt.xlabel('Type of Fuel')
plt.ylabel('Average Daily Rate ($)')
plt.tight_layout()
plt.legend(loc='upper center')
plt.savefig('dailyratefuel.png')
plt.show()
plt.clf()

#Scatter Plot of Rating vs. Number of Trips Taken
sns.set(style='whitegrid')
plt.figure(figsize=(8,5))
sns.scatterplot(data=df, x='rating', y='renterTripsTaken', alpha=0.6)
plt.title('Rating vs. Number of Trips Taken')
plt.suptitle('Higher Rated Vehicles Typically Go on More Trips', fontsize=10, y=0.95)
plt.xlabel('Rating')
plt.ylabel('Trips Taken')
plt.tight_layout()
plt.savefig('ratingvstripstaken.png')
plt.show()
plt.clf()

#Barchart of Number of Reviews by Vehicle Make
sns.set(style='whitegrid')
plt.figure(figsize=(20,6))
sns.barplot(data=df, x='vehicle.make', y='reviewCount', estimator=sum, ci=None, palette='Dark2')
plt.title('Number of Reviews by Vehicle Make')
plt.suptitle('Tesla, Toyota, Chevy, and BMW Get The Most Review Count (Positive or Negative?)', fontsize=10, y=0.95)
plt.xlabel('Vehicle Make')
plt.ylabel('Total Reviews')
plt.xticks(rotation=90)
plt.tight_layout()
plt.savefig('reviewsbymake.png')
plt.show()
plt.clf()