# -*- coding: utf-8 -*-
"""inst 760 project_1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12niWp5C2ShH_rY9QdtaXzwEwOJwfJWhJ
"""

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
sns.set_theme(style="whitegrid")
#Read CSV
df= pd.read_csv('cosmetics_sales_data.csv')

#Display First 5 Rows
df.head()

# Heatmap
pd_crosstab = pd.crosstab(df["Country"], df["Product"])

# Plot a heatmap of the table with no color bar and using the BuGn palette
sns.heatmap(pd_crosstab, cbar=False, cmap="BuGn", linewidths=0.3)

# Rotate tick marks for visibility
plt.title("Sales by Country and Product")
plt.yticks(rotation=0)
plt.xticks(rotation=90)

#Save/Show the plot
plt.savefig("heatmap.png")
plt.show()

#Lineplot
df['Date'] = pd.to_datetime(df['Date'])

sns.relplot(
    data=df,
    x='Date',
    y='Amount ($)',
    kind='line',
    ci=None,
    height=6,
    aspect=2
)
plt.title("Total Sales Amount Over Time")
plt.xlabel("Date (2022 Year)")
plt.xticks(rotation=45)
plt.savefig("lineplot.png")
plt.show()

#Scatterplot

sns.relplot(
    data=df,
    x="Boxes Shipped",
    y="Amount ($)",
    hue="Product",
    kind="scatter",
)
plt.title("Amount vs Boxes Shipped by Product")
plt.savefig("scatterplot.png")
plt.show()

#Boxplot
sns.boxplot(data=df, x="Product", y="Amount ($)")
plt.title("Sales Amount Distribution by Product")
plt.xticks(rotation=90)
plt.savefig("boxplot.png")
plt.show()

#Barplot

sns.barplot(
    data=df,
    x="Country",
    y="Amount ($)",
    hue="Country"
)
plt.xticks(rotation=45)
plt.savefig("barplot.png")
plt.show()